# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('aliases', models.TextField(blank=True, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
                ('members_count', models.IntegerField()),
                ('avatar_url', models.CharField(max_length=255)),
                ('is_public_readable', models.BooleanField()),
                ('is_guest_writeable', models.BooleanField()),
            ],
        ),
    ]
