# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rid',
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
