# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 17:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0006_auto_20171016_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymembers',
            options={'verbose_name_plural': 'Daily Members'},
        ),
        migrations.RemoveField(
            model_name='dailymembers',
            name='room',
        ),
        migrations.AddField(
            model_name='dailymembers',
            name='room_id',
            field=models.CharField(default='empty', max_length=511),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailymembers',
            name='date',
            field=models.DateField(default=datetime.datetime.now, editable=False),
        ),
    ]
