# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0011_auto_20171019_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
    ]
