# Generated by Django 2.0.1 on 2018-11-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_area', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.DeleteModel(
            name='BoundServer',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
