# Generated by Django 2.0.1 on 2018-11-05 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room_stats', '0032_room_federated_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_area', '0002_auto_20181104_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField()),
                ('verification_code', models.UUIDField(default=uuid.uuid4)),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room_stats.Server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
