# Generated by Django 2.0.1 on 2018-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_area', '0003_boundserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundserver',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
