# Generated by Django 2.0.1 on 2018-11-05 12:02

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('user_area', '0005_boundserver_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boundserver',
            name='ref_id',
        ),
        migrations.AlterField(
            model_name='boundserver',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
