# Generated by Django 2.0.1 on 2018-11-08 08:50

from django.db import migrations, models
import user_area.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_area', '0006_auto_20181105_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundserver',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boundserver',
            name='header',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='boundserver',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=user_area.models.upload_to),
        ),
        migrations.AddField(
            model_name='boundserver',
            name='payment_model',
            field=models.CharField(choices=[('f', 'Free'), ('p', 'Paid')], default='f', max_length=1),
        ),
        migrations.AddField(
            model_name='boundserver',
            name='registration',
            field=models.CharField(choices=[('o', 'Open'), ('r', 'Open (on-request)'), ('c', 'Closed'), ('t', 'Closed (temporarily)')], default='o', max_length=1),
        ),
        migrations.AddField(
            model_name='boundserver',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boundserver',
            name='server_load',
            field=models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High'), ('f', 'Full')], default='l', max_length=1),
        ),
    ]
