# Generated by Django 2.0.1 on 2018-11-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_area', '0007_auto_20181108_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundserver',
            name='maturity',
            field=models.CharField(choices=[('s', 'Stable'), ('e', 'Experimental')], default='s', max_length=1),
        ),
    ]
