# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0002_auto_20171016_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
