# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0003_auto_20171016_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(max_length=511, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
