# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0004_auto_20171016_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMembers',
            fields=[
                ('id', models.CharField(max_length=511, primary_key=True, serialize=False)),
                ('members_count', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_stats.Room')),
            ],
        ),
    ]
