# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0005_dailymembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymembers',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dailymembers',
            name='id',
            field=models.CharField(editable=False, max_length=511, primary_key=True, serialize=False),
        ),
    ]
