# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 17:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0012_remove_room_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=255)),
                ('latency', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
