# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0013_serverstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstats',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
