# Generated by Django 2.0.1 on 2018-01-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0014_auto_20171028_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_stats.Room')),
            ],
        ),
        migrations.AlterField(
            model_name='dailymembers',
            name='room_id',
            field=models.CharField(db_index=True, max_length=511),
        ),
    ]
