# Generated by Django 2.0.1 on 2018-01-25 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0015_auto_20180125_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymembers',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime.now, editable=False),
        ),
    ]
