# Generated by Django 2.0.1 on 2018-01-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0016_auto_20180125_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
