# Generated by Django 2.0.1 on 2018-03-23 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0019_auto_20180126_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('size', models.CharField(choices=[('s', 'small'), ('m', 'medium')], max_length=1)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remove_at', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_stats.Room')),
            ],
        ),
    ]
