# Generated by Django 2.0.1 on 2018-03-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0020_promotionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='categories',
            field=models.ManyToManyField(blank=True, to='room_stats.Category'),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_old', to='room_stats.Category'),
        ),
    ]
