# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0022_room_inactive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerStats',
        ),
    ]
