# Generated by Django 2.0.1 on 2018-04-05 17:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0024_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='last_response_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
