# Generated by Django 2.0.1 on 2018-04-06 07:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0026_auto_20180405_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
