# Generated by Django 2.0.1 on 2018-04-14 10:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import room_stats.models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0027_server_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStatisticalData',
            fields=[
                ('id', models.CharField(default=room_stats.models.RoomStatisticalData.make_id, max_length=530, primary_key=True, serialize=False, unique=True)),
                ('room_id', models.CharField(db_index=True, max_length=511)),
                ('period', models.CharField(choices=[('d', 'daily'), ('w', 'weekly'), ('m', 'monthly')], db_index=True, max_length=1)),
                ('starts_at', models.DateField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('messages_total', models.IntegerField()),
                ('senders_total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('a', 'assumed'), ('c', 'confirmed'), ('n', 'not_exist'), ('d', 'registration_disabled'), ('r', 'registered'), ('u', 'unknown')], default='a', max_length=1),
        ),
    ]
