# Generated by Django 2.0.1 on 2018-04-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0028_auto_20180414_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomstatisticaldata',
            options={'verbose_name_plural': 'room statistical data'},
        ),
        migrations.AddField(
            model_name='server',
            name='sync_interval',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='roomstatisticaldata',
            name='id',
            field=models.CharField(max_length=530, primary_key=True, serialize=False, unique=True),
        ),
    ]
