# Generated by Django 2.0.1 on 2018-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0029_auto_20180420_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='sync_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
