# Generated by Django 2.0.1 on 2018-04-21 10:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0031_server_last_sync_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='federated_with',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
