# Generated by Django 2.0.1 on 2018-11-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_stats', '0032_room_federated_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='sync_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='sync_interval',
            field=models.IntegerField(default=600),
        ),
    ]
